# =====================================================
# SERVER
# =====================================================

server.port=8083

# =====================================================
# APPLICATION NAME
# =====================================================

spring.application.name=notification-service

# =====================================================
# EUREKA
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# =====================================================
# MAILJET
# =====================================================

mailjet.api-key=262c9c88fb9b4b5b2bc6163003b65ca2
mailjet.secret-key=99aa5aa44425bb2addd56bc3961e1c29

# =====================================================
# LOGGING
# =====================================================

logging.level.root=INFO
logging.level.com.auction.notification_service=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n
logging.file.name=logs/notification-service.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=200MB

# =====================================================
# RESILIENCE4J CIRCUIT BREAKER
# =====================================================

resilience4j.circuitbreaker.instances.emailService.registerHealthIndicator=true

resilience4j.circuitbreaker.instances.emailService.slidingWindowSize=5

resilience4j.circuitbreaker.instances.emailService.minimumNumberOfCalls=3

resilience4j.circuitbreaker.instances.emailService.failureRateThreshold=50

resilience4j.circuitbreaker.instances.emailService.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.emailService.permittedNumberOfCallsInHalfOpenState=2

# =====================================================
# RETRY
# =====================================================

resilience4j.retry.instances.emailService.maxAttempts=3

resilience4j.retry.instances.emailService.waitDuration=2s

# =====================================================
# ACTUATOR
# =====================================================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =====================================================
# KAFKA
# =====================================================

spring.kafka.bootstrap-servers=localhost:9092

# =====================================================
# CONSUMER
# =====================================================

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

# =====================================================
# LISTENER
# =====================================================

spring.kafka.listener.ack-mode=record

# =====================================================
# KAFKA RETRY
# =====================================================

resilience4j.retry.instances.notificationRetry.maxAttempts=3

resilience4j.retry.instances.notificationRetry.waitDuration=2s