spring.application.name=NOTIFICATION-SERVICE

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

mailjet.api-key: 262c9c88fb9b4b5b2bc6163003b65ca2
mailjet.secret-key: 99aa5aa44425bb2addd56bc3961e1c29