spring.application.name=eurka-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.file.name=logs/eureka-server.log
logging.level.root=INFO


logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n