
spring.application.name=api-gateway
server.port=8080

spring.main.web-application-type=reactive

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# =========================
# USER SERVICE
# =========================
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

# =========================
# ITEM SERVICE
# =========================
spring.cloud.gateway.routes[1].id=item-service
spring.cloud.gateway.routes[1].uri=lb://ITEM-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/items/**,/api/item-admin/**

# =========================
# AUCTION SERVICE
# =========================
spring.cloud.gateway.routes[2].id=auction-service
spring.cloud.gateway.routes[2].uri=lb://AUCTION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auctions/**,/api/auction-admin/**

logging.file.name=logs/api-gateway.log
logging.level.root=INFO

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n