# =====================================================
# SERVER CONFIG
# =====================================================

server.port=8084

# =====================================================
# APPLICATION NAME
# =====================================================

spring.application.name=auction-service

# =====================================================
# MYSQL DATABASE CONFIG
# =====================================================

spring.datasource.url=jdbc:mysql://localhost:3306/auction_dashboard
spring.datasource.username=root
spring.datasource.password=your_password

# =====================================================
# JPA / HIBERNATE CONFIG
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =====================================================
# EUREKA CONFIG
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# =====================================================
# LOGGING CONFIG
# =====================================================

logging.level.root=INFO
logging.level.com.auction=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG


# =====================================================
# FILE LOGGING
# =====================================================

logging.file.name=logs/auction-service.log

# LOG ROTATION

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=200MB



# =====================================================
# ACTUATOR CONFIG
# =====================================================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n

# =====================================================
# KAFKA
# =====================================================
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer